services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - URL=${URL_MAIN:-http://localhost:3000}
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true